const Discord = require("discord.js");
const bot = new Discord.Client();
const fs = require("fs")
exports.run = async (client, message, args) => {
    let user = message.mentions.users.first();
    if (message.mentions.users === message.author.username) return message.reply('Vous ne pouvez pas vous complimenter vous-même.');
    if (message.mentions.users.size < 1) return message.reply('Vous devez mentionner quelqu\'un pour le complimenter.')
    var roast = [
        "ton sourire est contagieux.",
        "tu es superbe aujourd’hui.",
        "tu es une fille intelligente.",
        "je parie que tu fais sourire les bébés.",
        "tu as des manières irréprochables.",
        "j'aime ton style.",
        "tu as le meilleur rire.",
        "je t'apprécie.",
        "tu es le plus parfait de tous.",
        "tu me suffis.",
        "tu es fort.",
        "ton point de vue est rafraîchissant.",
        "tu es un super ami.",
        "tu illumines la pièce.",
        "tu brilles plus qu'une étoile filante.",
        "tu mérites un câlin là maintenant.",
        "tu devrais être fier de toi.",
        "tu es plus utile que tu ne le penses.",
        "tu as un grand sens de l'humour.",
        "tu assures.",
        "c’est ta photo à côté de 'charmant(e)' dans le dictionnaire ?",
        "ta bonté est un baume pour tous ceux qui la rencontrent.",
        "tu es tout ça et un super sac de chips.",
        "sur une échelle de 1 à 10, tu es un 11.",
        "tu es courageux.",
        "tu es encore plus belle à l'intérieur qu'à l'extérieur.",
        "tu avez le courage de tes convictions.",
        "tes yeux sont à couper le souffle.",
        "si les oiseaux bleus de dessins animés étaient réels, un tas d’entre eux serait assis sur tes épaules chantant en ce moment.",
        "tu fais une différence.",
        "tu es comme le soleil quand il pleut.",
        "tu fais ressortir le meilleur chez les autres.",
        "ta capacité à rappeler des faits aléatoires au bon moment est impressionnante.",
        "tu sais écouter.",
        "comment se fait-il que tu sois toujours superbe, même en survêtement ?",
        "tout irait mieux si plus de gens étaient comme toi !",
        "je parie que tu transpires des paillettes.",
        "tu étais cool avant que les hipsters soient cool.",
        "cette couleur est parfaite sur toi.",
        "traîner avec toi est toujours un plaisir.",
        "tu sais toujours -- et dis -- exactement ce que j’ai besoin d’entendre quand j’en ai besoin.",
        "tu sens vraiment bon.",
        "tu danses peut-être comme si personne ne te regardait, mais tout le monde te regarde parce que tu es un danseur incroyable!",
        "être près de toi rend tout meilleur !",
        "quand tu dis 'Je voulais faire ça', je te crois totalement.",
        "quand tu n’as pas peur d’être toi-même c’est quand tu es le plus incroyable.",
        "les couleurs semblent plus brillantes quand tu es près.",
        "tu es plus drôle qu’une boule remplie de bonbons. (Et sérieusement, qu’est-ce qui pourrait être plus amusant que ça ?)",
        "ce que tu n’aimes pas chez toi-même est ce qui te rend si intéressant.",
        "tu es merveilleux.",
        "tu as de jolis coudes. Pour de vrai!",
        "les blagues sont plus drôles quand tu les dis.",
        "tu vaux mieux qu’un cornet de crème glacée à trois boules. Avec des saupoudres.",
        "ton nombril est adorable.",
        "tes cheveux sont magnifiques.",
        "tu es unique en son genre!",
        "tu es une source d’inspiration.",
        "si tu étais une boîte de crayons, tu serais la marque géante avec le taille-crayon intégré.",
        "tu devrais être remercié plus souvent. Alors merci!!",
        "notre communauté est meilleure parce que tu en fais partie.",
        "quelqu’un traverse quelque chose de dur en ce moment parce que tu es derrière lui.",
        "tu as les meilleures idées.",
        "tu sais toujours comment trouver ce bon côté.",
        "tout le monde se fait assommer parfois, mais tu te relève toujours et continue.",
        "tu es une bougie dans les ténèbres.",
        "tu es un excellent exemple pour les autres.",
        "être près de toi, c’est comme être en vacances.",
        "tu sais toujours quoi dire.",
        "tu apprends toujours de nouvelles choses et tu essaies de t’améliorer, ce qui est génial.",
        "si quelqu’un a basé un meme sur toi, il doit avoir une grammaire impeccable.",
        "tu pourrais survivre à une apocalypse zombie.",
        "tu es plus drôle que du papier bulle.",
        "quand tu fais une erreur, tu la répares.",
        "Qui t'as élevé? Ils méritent une médaille pour un travail bien fait.",
        "tu es doué pour comprendre les choses.",
        "ta voix est magnifique.",
        "les gens que tu aimes ont de la chance de t’avoir dans leur vie.",
        "tu es comme une bouffée d’air frais.",
        "tu es magnifique -- et c’est la chose la moins intéressante chez toi aussi.",
        "tu es si attentionné.",
        "ton potentiel créatif semble sans limites.",
        "ton nom te va bien.",
        "tu es irrésistible quand tu rougis.",
        "les actions parlent plus fort que les mots, et les tiennes racontent une histoire incroyable.",
        "d’une façon ou d’une autre, tu fais arrêter le temps et voler en même temps.",
        "quand tu te décides pour quelque chose, rien ne se met en travers de ton chemin.",
        "tu sembles vraiment savoir qui tu es.",
        "n’importe quelle équipe serait chanceuse de t'avoir sur elle.",
        "au lycée, je parie que tu as été élue la plus susceptible de continuer à être génial.'",
        "je parie que tu fais les mots croisés à l’encre.",
        "les bébés et les petits animaux t'aiment probablement.",
        "si tu étais une bougie parfumée ils l’appelleraient Parfaitement Imparfait (et il sentirait comme l’été).",
        "il y a l’ordinaire, et puis il y a toi.",
        "tu es une raison de sourire.",
        "tu es encore meilleur qu’une licorne, parce que tu es réel.",
        "comment peux-tu continuer à être si drôle et à faire rire tout le monde ?",
        "tu as une bonne tête sur les épaules.",
        "on t’a déjà dit que tu avais une bonne posture ?",
        "la façon dont tu chéris tes proches est incroyable.",
        "tu es vraiment quelque chose de spécial.",
        "tu es un cadeau pour ceux qui t’entourent.",
        "tu ne le mérites pas."
]
    const roasts = roast[Math.floor(Math.random() * roast.length)];
    const embed = new Discord.RichEmbed()
        .setColor(0x7700cf)
        .setDescription(user.username + ", " + roasts);
    message.channel.send({embed})
  }